### ISSUE TITLE
Maintain this project

### ISSUE THREAD

**Issue by cniweb** [Ericbla/check_jenkins#4]
@Ericbla Do you continue to support and maintain this project?
If you do not have time, I could take it.

Thanks,
Chris

**Comment by Ericbla** [comment]
Hi @cniweb 
Thanks for your interest on that project.

As you noticed, I have not worked on it since a long time (and I currently have no real infrastructure with Nagios to be able to maintain the project and accept pull requests).

So feel free to fork and continue on your side.

If you really do that, please let me know, so I can put a link in the Readme of this project to redirect people toward your new project.

Best regards.

--
Eric
